src/Entity/Beer.php
<?php

namespace App\Entity;

use App\Repository\BeerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BeerRepository::class)
 */
class Beer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $published_at;

    /**
     * @ORM\ManyToOne(targetEntity=Country::class, inversedBy="beers")
     */
    private $country;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="beers")
     */
    private $categories;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2, nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $degree;

    /**
     * @ORM\OneToMany(targetEntity=Statistic::class, mappedBy="beer_id", orphanRemoval=true)
     */
    private $statistics;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->statistics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDegree(): ?string
    {
        return $this->degree;
    }

    public function setDegree(string $degree): self
    {
        $this->degree = $degree;

        return $this;
    }

    /**
     * @return Collection|Statistic[]
     */
    public function getStatistics(): Collection
    {
        return $this->statistics;
    }

    public function addStatistic(Statistic $statistic): self
    {
        if (!$this->statistics->contains($statistic)) {
            $this->statistics[] = $statistic;
            $statistic->setBeerId($this);
        }

        return $this;
    }

    public function removeStatistic(Statistic $statistic): self
    {
        if ($this->statistics->removeElement($statistic)) {
            // set the owning side to null (unless already changed)
            if ($statistic->getBeerId() === $this) {
                $statistic->setBeerId(null);
            }
        }

        return $this;
    }

}

templates/beers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
  <h5 class="py-6 text-xl font-bold text-primary">{{ title }}</h5>

  <div class="flex flex-wrap">
  {% for beer in beers %}
      {{render(controller('App\\Controller\\BarController:card_beer', {'beer': beer}))}}
  {% endfor %}
  </div>
{% endblock %}

templates/beers/sigle_beer.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ title }}{% endblock %}

  {% block body %}

    <h5 class="py-10 text-2xl text-primary">{{ beer.name }}</h5>
    <p><small>Date d'invention : {{ beer.publishedAt | date('d/m/Y h:i:s') }} </small></p>
    <img src="{{ asset('build/images/beer_picture.png') }}" />
    {# Affichez les catégories dans lesquelles se trouvent vos bières  #}
    <p>Price : {{ beer.price ?? 'aucune information' }} </p>
    <p>Degree : {{ beer.degree }} </p>
    <p>{{ beer.country ? beer.country.name : ''}} </p>
    <p>{{ beer.description }}</p>
{% endblock %}